version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/digidesk
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - mern-net

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - mern-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/digidesk.no.conf:/etc/nginx/conf.d/digidesk.no.conf
      - ./nginx/digidesk.one.conf:/etc/nginx/conf.d/digidesk.one.conf
      - ./nginx/ssl:/etc/ssl/private
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - mern-net

volumes:
  mongo-data:

networks:
  mern-net:
    driver: bridge
