services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-net
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/digidesk
    env_file:
      - ./backend/.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mern-net
    restart: always
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    networks:
      - mern-net
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/digidesk.no.conf:/etc/nginx/conf.d/digidesk.no.conf
      - ./nginx/digidesk.one.conf:/etc/nginx/conf.d/digidesk.one.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/build:/usr/share/nginx/html
      - ./backend/uploads:/usr/share/nginx/html/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - mern-net
    restart: always

volumes:
  mongo-data:

networks:
  mern-net:
    driver: bridge
